### ISSUE TITLE
1.4.7_0665 no curl command

### ISSUE THREAD

**Issue by itispip** [niceboygithub/XiaomiGateway3fw#3]
can next fw update add back curl?

**Comment by serrj-sv** [comment]
> can next fw update add back curl?

you can use this custom firmware, it has curl:
https://github.com/serrj-sv/lumi.gateway.mgl03/tree/main/firmware/custom/mgl03_1.4.7_0065_mod20201211

download zip, then use this guide to flash:
https://gist.github.com/zvldz/b40b4873e3c4c1a64ac536e8ce5dbdad
